services:
  db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
